### ISSUE TITLE
Heart Rate Zones

### ISSUE THREAD

**Issue by lisaannyu** [corynissen/fitbitScraper#13]
Hi Cory,

When I run fitbitScraper::get_daily_data(cookie = cookie, what = "getTimeInHeartRateZonesPerDay", start_date = "2017-03-12", end_date = "2017-03-12") multiple times, sometimes the last column is IN_DEFAULT_ZONE_2 and sometimes the last column is IN_DEFAULT_ZONE_3.  Furthermore, zone1, zone2, and IN_DEFAULT_ZONE[2|3] does not seem to consistently match to "peak", "fat_burn", "cardio".  Is this something you can shed light on?  I know fitbit's API is not friendly.  Thanks!

**Comment by corynissen** [comment]
Fixed in github, submitting to CRAN soon
