### ISSUE TITLE
Request: include additional field options 

### ISSUE THREAD

**Issue by mariellep** [corynissen/fitbitScraper#14]
Current options for data export: "steps", "distance", "floors", "minutesVery", "caloriesBurnedVsIntake"

Would like to be able to import "minutes lightly active" and "minutes fairly active" as well as "sedentary minutes" (or whatever it's called within the system). I'll play around with the code too and see if I can come up with something that I can contribute to the package, but since you already know how to do it I figured I'd ask!

**Comment by corynissen** [comment]
Was able to add one of your requests. I can't figure out the other ones for now. Submitting to CRAN soon
