### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by MaMeh** [corynissen/fitbitScraper#8]
Hi guys,
please forgive me if I'm completly at the wrong place...
I am new to R and these kind of scripts. Is it possible to give me some hints how to use the fitbitScraper? Maybe a link to a step-by-step instruction?
Do I have to copy-paste all the login and get-\* scripts into one, adapt it to my personal data and just run it in RGui and where will the data received from fitbit be stored?
Again, I apologize for maybe being seriously off-topic here!

**Comment by corynissen** [comment]
There's an example of login and two get-\* functions in the README file... https://github.com/corynissen/fitbitScraper/blob/master/README.md

I made a blog post too that uses a couple of the functions... http://blog.corynissen.com/2015/03/fitbitscraper-012-now-on-cran.html

There's examples in the help documents for each function.

You will have to learn R to use this R library. I leave it to you to find the resources required to do that.
