### ISSUE TITLE
get_daily_data Line 60

### ISSUE THREAD

**Issue by Esturban** [corynissen/fitbitScraper#9]
Hi Cory,
I wanted to thank you for fitbitScraper package.  It has made pulling fitbit data very efficient and far more effective than Excel certainly would have.  
Just noticed a small typo which generates an error, but does not impede the output.  Changing the 3 to a 4 gives you the desired result without the warning.
  if(what=="getTimeInHeartRateZonesPerDay"){
    df <- cbind(dat_list$dateTime, dat_list$value, stringsAsFactors=FALSE)
    **names(df)[1:3] <- c("time", "zone1", "zone2", "zone3")**
Thanks again for the library!

Esturban

**Comment by corynissen** [comment]
Fixed in github, submitting to CRAN soon
